# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: deploy

on:
  push:
    branches: [deploy]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm install
        run: npm install
      - name: client build
        run: npm run build
      - name: deploy
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp

          # Credentials for SFTP access to server using GitHub secrets
          remote-host: ${{ secrets.CLIENT_HOST }}
          remote-user: ${{ secrets.CLIENT_USER }}
          remote-password: ${{ secrets.CLIENT_SERVER_PASSWORD }}

          # Path for specific folder on server for files deployment
          remote-path: /var/www/html

          # Port for SFTP access to server
          remote-port: 22

          # Local path for files to deploy
          local-path: ./out

          sync: full
