# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: deploy

on:
  push:
    branches: [deploy]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm install
        working-directory: tally-light-client
        run: npm install
      - name: client build
        working-directory: tally-light-client
        run: npm run build

      - name: deploy
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.CLIENT_HOST }}
          remote-user: ${{ secrets.CLIENT_USER }}
          remote-password: ${{ secrets.CLIENT_SERVER_PASSWORD }}
          remote-path: /var/www/html
          remote-port: 22
          local-path: tally-light-client/out
          sync: full
